# Generated by Django 5.2.7 on 2025-10-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_url_offercategory_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
